  language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements.txt
  script:
    - nosetests --rednose _tests_ -v -d
  after_success:
    - codecov --token=21103fe1-7292-4e2b-a689-bca582c24523
