  language: python
  python:
    - "3.6"
  install:
    - pip install -r requirements.txt
  script:
    - nosetests --rednose _tests_ -v -d
  after_success:
    - CODACY_PROJECT_TOKEN=21ad9645051e4b398c27c3e7a53e2bad python-codacy-coverage -r coverage.xml
